### ISSUE TITLE
Change project name to lazaret

### ISSUE THREAD

**Issue by enj** [enj/kms#22]
And update all the paths and such.

**Comment by enj** [comment]
@npmccallum @benjaminapetersen @lancejjohnson other suggestions welcome.

**Comment by benjaminapetersen** [comment]
but...but....but....

![image](https://user-images.githubusercontent.com/280512/37797042-260844b8-2def-11e8-9eac-4be89a17413c.png)

now can't have this 😢 😞 😭 

#panda for life.

**Comment by lancejjohnson** [comment]
lazaretto

**Comment by enj** [comment]
> lazaretto

lazaret sounds more like a project name?

**Comment by lancejjohnson** [comment]
lazaretto sounds more fun. ends in a nice round sound rather than a hard
stop on that t.

**Comment by benjaminapetersen** [comment]
definition:

```
Lazaret (also Lazarette or Lazaretto)
1.  A small stowage locker at the aft end of a boat.
2.  A ship or building used for quarantine of sick patients.
3.  An area on some merchant ships where provisions are stored.
4.  In modern shipbuilding and on powerboats of all sizes, the location of the steering gear equipment for the vessel.
```
Modern usage is #4, will that throw people off?

**Comment by npmccallum** [comment]
I prefer brig. Lazaret is more obscure and the modern usage isn't relevant.

**Comment by enj** [comment]
> I prefer brig. Lazaret is more obscure and the modern usage isn't relevant.

brig has a negative connotation IMHO.

**Comment by enj** [comment]
Some more nautical options:

```
Barbette
    1.  During the second half of the 19th century, a fixed armored enclosure protecting a ship's guns aboard warships without gun turrets, generally taking the form of a ring of armor over which guns mounted on an open-topped rotating turntable could fire.
    2.  Since the late 19th century, the inside fixed trunk of a warship's turreted gun-mounting, on which the turret revolves, containing the hoists for shells and cordite from the shell-room and magazine.
```

```
Citadel
    A fortified safe room on a vessel to take shelter in the event of pirate attack. Previously, a fortified room to protect ammunition and machinery from damage.
```

```
Hammock
    Canvas sheets, slung from the deckhead in messdecks, in which seamen slept. "Lash up and stow" a piped command to tie up hammocks and stow them (typically) in racks inboard of the ship's side to protect crew from splinters from shot and provide a ready means of preventing flooding caused by damage.
```

---

`citadel` is probably my favorite so far.

**Comment by enj** [comment]
`citadel` also flows well with `vault` which everyone seems to use in this space.

**Comment by npmccallum** [comment]
We could focus on the concept of tying the boat to the shore to keep it safe. We are (usually) tying Kube to the network (or some other entity). Terms that might apply:

* moor
* mooring
* berth
* chock
* hawser

**Comment by npmccallum** [comment]
I'm kind of partial to `chock`:

![Chock](https://fas.org/man/dod-101/sys/ship/image1450.gif)

**Comment by npmccallum** [comment]
Oh, I just noticed `citadel`. I like that.

**Comment by benjaminapetersen** [comment]
`citadel` has most exciting sound & people know what it is..... but its also probably really popular.  If you google it, might have a lot of stuff to sift through.

**Comment by lancejjohnson** [comment]
With `citadel` searches would turn up lots of young men in uniform with
crew cuts so the sifting would at least be pleasant
